"""added group table  and admins relationship

Revision ID: 607b3775a59a
Revises: 512209c000b9
Create Date: 2025-12-08 19:34:14.533771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607b3775a59a'
down_revision: Union[str, Sequence[str], None] = '512209c000b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('added_by_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_status', sa.String(length=20), nullable=False),
    sa.Column('admin_permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by_telegram_id'], ['users.telegram_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_group_telegram_id'), 'groups', ['group_telegram_id'], unique=True)
    op.create_table('group_admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('admin_permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group_admin')
    )
    op.create_index('idx_group_admin_group_id', 'group_admins', ['group_id'], unique=False)
    op.create_index('idx_group_admin_user_id', 'group_admins', ['user_id'], unique=False)
    op.add_column('user_schedule_task', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_schedule_task_telegram_id_key'), 'user_schedule_task', type_='unique')
    op.create_unique_constraint(None, 'user_schedule_task', ['user_id'])
    op.drop_constraint(op.f('user_schedule_task_telegram_id_fkey'), 'user_schedule_task', type_='foreignkey')
    op.create_foreign_key(None, 'user_schedule_task', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_schedule_task', 'telegram_id')
    op.drop_column('users', 'tz_offset')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tz_offset', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('user_schedule_task', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_schedule_task', type_='foreignkey')
    op.create_foreign_key(op.f('user_schedule_task_telegram_id_fkey'), 'user_schedule_task', 'users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_schedule_task', type_='unique')
    op.create_unique_constraint(op.f('user_schedule_task_telegram_id_key'), 'user_schedule_task', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_schedule_task', 'user_id')
    op.drop_index('idx_group_admin_user_id', table_name='group_admins')
    op.drop_index('idx_group_admin_group_id', table_name='group_admins')
    op.drop_table('group_admins')
    op.drop_index(op.f('ix_groups_group_telegram_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
