"""add columns in group and group tasks models

Revision ID: cd2c59346601
Revises: d5b1be690fa3
Create Date: 2025-12-14 13:20:17.149049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd2c59346601'
down_revision: Union[str, Sequence[str], None] = 'd5b1be690fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_daily_tasks', sa.Column('task_number', sa.Integer(), nullable=False))
    op.add_column('group_daily_tasks', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('group_daily_tasks', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('group_daily_tasks', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('group_daily_tasks', sa.Column('language_code', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('group_daily_tasks_group_id_key'), 'group_daily_tasks', type_='unique')
    op.create_unique_constraint('uq_group_task_number', 'group_daily_tasks', ['group_id', 'task_number'])
    op.add_column('groups', sa.Column('tz_region', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'tz_region')
    op.drop_constraint('uq_group_task_number', 'group_daily_tasks', type_='unique')
    op.create_unique_constraint(op.f('group_daily_tasks_group_id_key'), 'group_daily_tasks', ['group_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('group_daily_tasks', 'language_code')
    op.drop_column('group_daily_tasks', 'longitude')
    op.drop_column('group_daily_tasks', 'latitude')
    op.drop_column('group_daily_tasks', 'city')
    op.drop_column('group_daily_tasks', 'task_number')
    # ### end Alembic commands ###
