"""del lang for groups tasks

Revision ID: d5ff452f309c
Revises: cd2c59346601
Create Date: 2025-12-16 20:56:26.721384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ff452f309c'
down_revision: Union[str, Sequence[str], None] = 'cd2c59346601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_daily_tasks', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_daily_tasks', sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
