name: Deploy Weather Bot to Server

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**.md'
      - 'assets/**'

concurrency:
  group: production-deploy
  cancel-in-progress: true

run-name: "Deploy bot to server"

env:
  PROJECT_DIR: "/ruslan/projects/weather-telegram-bot"
  SERVICE_NAME: "weather-telegram-bot"
  DOCKER_SERVICE_NAME: "weather-telegram-bot-docker"
  WORKER_SERVICE_NAME: "weather-telegram-bot-worker"
  SCHEDULER_SERVICE_NAME: "weather-telegram-bot-scheduler"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Git clone repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          clean: true

      - name: Check project structure
        run: |
          echo "📁 current directory:"
          ls -la

      - name: Deploy project directory to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ env.PROJECT_DIR }}
          ARGS: >-
            -rlgoDzvi --delete
            --exclude=.env
            --exclude=.nui_data
            --exclude=.pgadmin_data
            --exclude=.postgres_data
            --exclude=.redis_data
            --exclude=.venv
            --exclude=.nats_data
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            sudo mkdir -p ${{ env.PROJECT_DIR }}
          SCRIPT_AFTER: |
            ls -al
            echo $RSYNC_STDOUT
            
            sudo systemctl restart ${{ env.DOCKER_SERVICE_NAME }}
            sudo systemctl restart ${{ env.SERVICE_NAME }}
            sudo systemctl restart ${{ env.WORKER_SERVICE_NAME }}
            sudo systemctl restart ${{ env.SCHEDULER_SERVICE_NAME }}
            
            sudo systemctl status ${{ env.DOCKER_SERVICE_NAME }}
            sudo systemctl status ${{ env.SERVICE_NAME }} --no-pager
            sudo systemctl status ${{ env.WORKER_SERVICE_NAME }} --no-pager
            sudo systemctl status ${{ env.SCHEDULER_SERVICE_NAME }} --no-pager