name: Deploy Weather Bot to Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

run-name: "Deploy bot to server"
# env values
env:
  PROJECT_DIR: "/${{ secrets.SERVER_USERNAME }}/projects/weather-telegram-bot"
  SERVICE_NAME: "weather-telegram-bot"
  DOCKER_SERVICE_NAME: "weather-telegram-bot-docker"
  WORKER_SERVICE_NAME: "weather-telegram-bot-worker"
  SCHEDULER_SERVICE_NAME: "weather-telegram-bot-scheduler"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Git clone repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check project structure
        run: |
          echo "📁 current directory:"
          ls -la

      - name: Deploy project directory to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ env.PROJECT_DIR }}
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            mkdir -p ${{ env.PROJECT_DIR }}
            find ${{ env.PROJECT_DIR }} -maxdepth 1 ! -name ".env*" ! -name ".*" ! -name "${{ env.PROJECT_DIR }}" -exec rm -rf {} + 2>/dev/null || true
          SCRIPT_AFTER: |
            ls -al
            echo $RSYNC_STDOUT

